# nfpm example config file
#
# check https://nfpm.goreleaser.com/configuration for detailed usage
#
name: "avnav-obp-plotterv3-plugin"
arch: "all"
platform: "linux"
version: "v1.0.0"
version_schema: "none"
section: "default"
priority: "extra"
depends:
- avnav
- python3-smbus
- python3-rpi.gpio
maintainer: "Andreas Vogel <andreas@wellenvogel.de>"
description: |
  AvNav plugin to handle obp-plotterv3
homepage: "https://example.com"
license: "MIT"
contents:
- src: ./plugin.*
  dst: /usr/lib/avnav/plugins/obp-plotterv3
- src: ./pwm.py
  dst: /usr/lib/avnav/plugins/obp-plotterv3/pwm.py
- src: ./setup.sh
  dst: /usr/lib/avnav/plugins/obp-plotterv3/setup.sh  
deb:
  fields:
    avnav-plugin: system-obp-plotterv3

